/**
 * og-image.js · Cloudflare Workers — módulo importado por worker.js
 * ─────────────────────────────────────────────────────────────────────────
 * Genera una imagen OG dinámica en PNG (1200×630 px) con el contador
 * de días restantes del gobierno calculado en tiempo real.
 *
 * Ruta pública: https://yafaltamenos.cl/og-image
 * Cache:        1 hora en CDN (s-maxage=3600)
 *
 * Fuente:  Oswald Bold — subsetted (~12 KB), embedida como base64.
 *          Decode sincrónico en module-load, reutilizada en cada request.
 * NOTA:    el WASM de resvg (~3.5 MB) requiere Workers Paid ($5/mes).
 * ─────────────────────────────────────────────────────────────────────────
 */

import { Resvg, initWasm } from '@resvg/resvg-wasm';
import resvgWasm from '@resvg/resvg-wasm/index_bg.wasm';

// Oswald Bold subsetted — solo caracteres usados en el OG image (~12 KB TTF)
// Decodificado una vez al cargar el módulo; reutilizado en cada render.
const OSWALD_B64 =
  'AAEAAAAPAIAAAwBwR0RFRgeTBUQAAB9wAAAAckdQT1OUsZQzAAAf5AAADfRHU1VCNMs64gAALdgAAAGQT1MvMot+faAAABvkAAAA' +
  'YFNUQVR5lWtJAAAvaAAAACpjbWFwC/YKvwAAHEQAAAEWZ2FzcAAAABAAAB9oAAAACGdseWa81ujJAAAA/AAAGFZoZWFkGnPnDQAA' +
  'GigAAAA2aGhlYQk7AxgAABvAAAAAJGhtdHikgwzaAAAaYAAAAV5sb2NhAbD7gQAAGXQAAACybWF4cABoAM8AABlUAAAAIG5hbWUq' +
  'dUcJAAAdXAAAAepwb3N0/58AMgAAH0gAAAAgAAIAFQAAAhEDKgAHAAoAADMTMxMjJyMHEzMDFZnMl6UbdxwsVisDKvzWq6sBFgE8' +
  '//8AFQAAAhEEMwImAAEAAAAHAFcBFADoAAMAPAAAAioDKgAUAB4AKQAAMxEzMh4CFRQGBgceAhUUDgIjJzMyNjU0JiYjIzUzMjY2' +
  'NTQmJiMjPNM0XUgpHTUlL0AhIT5bO0YmOy0ULiclIykqDxctIh8DKhAtU0QxQygHBjFSOj9bOhx9PDouNhl2GTAiICsWAAEAMf/0' +
  'Ag0DNQAnAAAFIiYmNRE0NjYzMhYWFRUjNTQmJiMiBgYVERQWFjMyNjY1NTMVFAYGASRcaywsa1xaZSqvBRgdHBsHCRsaHBgGryll' +
  'DEN5UgEkVHlCO2pFRlEYLB0eLRn+gxstGx0uGFVGRW0/AAIAPAAAAhkDKgALABcAADMRMzIWFhURFAYGIyczMjY2NRE0JiYjIzzN' +
  'anYwMHVpHBwpJAkLJCgbAyo1cVr+2ltzNnwYMCQBYSQsFAABADwAAAGqAyoACwAAMxEhFSMVMxUjFTMVPAFsuY2NuwMqesl88nn/' +
  '/wA8AAABqgQzAiYABgAAAAcAVwD0AOgAAQA8AAABmgMqAAkAADMRIRUjFTMVIxE8AV6rlZUDKnnMff6YAAABADH/9AISAzUAKgAA' +
  'BSImJjURNDY2MzIWFhUVIzU0JiYjIgYGFREUFhYzMjY2NTUjNTMRIycGBgEPVGEpLGtcWmcsrwcZHB0aBwsdGxweDEnqdgoQPgxG' +
  'f1MBEFZ+RTxqRzRCGiwbHy4Z/okbLx0eMBtfaf5cQyItAAEAPwAAAiMDKgALAAAzETMRMxEzESMRIxE/s36zs34DKv64AUj81gFi' +
  '/p4AAQA9AAAA8AMqAAMAADMRMxE9swMq/Nb//wA9AAABRQQzAiYACwAAAAcAVwCWAOgAAQAN/+sBIQMqAA0AABc1Mj4CNREzERQG' +
  'BiMNGyYWCrMhUkoVfQYRIRoCcP2IQlksAAABADwAAAItAyoACwAAMxEzERMzAxMjAwcRPLOIr5adtnUTAyr+tQFL/pL+RAFmIP66' +
  'AAEAPAAAAakDKgAFAAAzETMRMxU8s7oDKv1PeQABADkAAAKHAyoADAAAMxMzExMzEyMDAyMDAzkOwFlguQ5/D15xZAwDKv4pAdf8' +
  '1gIb/eUCH/3hAAEAPAAAAfQDKgAJAAAzETMTETMRIwMRPH6mlHmmAyr+egGG/NYBpP5cAAIAMf/0AhkDNQARACMAAAUiJiY1ETQ2' +
  'NjMyFhYVERQGBicyNjY1ETQmJiMiBgYVERQWFgEkW2ouLmpbXGsuLmtcHBoICBocGhoIBxkMQHhTAS1Udj8/dlT+01N4QH8cLBcB' +
  'hhgrHBwrGP56FywcAP//ADH/9AIZBDMCJgASAAAABwBXASUA6AACADwAAAIhAyoADAAXAAAzESEyFhYVFAYGIyMRETMyNjY1NCYm' +
  'IyM8ARBJXi4+akJIPCEiCwkiJDsDKjdpS15jJv6oAdUYMCUfLxwAAgAx/2ECGQM1AB0ALwAABS4CJwYiIyImJjURNDY2MzIWFhUR' +
  'FAYGBx4CFycyNjY1ETQmJiMiBgYVERQWFgHbFj49FQQIBVtqLi5qW1xrLhUvJw0cHA7dHBoICBocHBkHBxmfCi09IAFAeFMBLVR2' +
  'Pz92VP7TOVxEFA4bFweoHCwXAYYYKxwcKxj+ehcsHAAAAgA8AAACNAMqAA8AGQAAMxEzMhYWFRQGBgcTIwMjEREzMjY2NTQmIyM8' +
  '31J4QxArKG+5WTMyJioRJjM6AyokXVUyTjkT/ngBa/6VAdIbMyQ0OgAAAQAq//QB5wM1AC0AAAUiJiYnNx4CMzI2NTQmJycmJjU0' +
  'NjMyHgIXBy4CIyIGFRQWFxcWFhUUBgYBE0xmNAOZAREfFhwRMClGLj96aUFPKQ8BmgEHFhcZFysjQzVJNF8MNnFaFzRAHCYVMkUj' +
  'PSdjSWdtLEdPJBMkNR0qFS05HzstclQ5XTYAAAEACwAAAbIDKgAHAAAzESM1IRUjEYV6Aad5AqWFhf1bAAABADb/9AIWAyoAFQAA' +
  'BSImJjURMxEUFhYzMjY2NREzERQGBgEmXWkqsQgbHB0aB7IraAw9dVUCL/22GTIgIDIZAkr90VV1Pf//ADb/9AIWBDMCJgAZAAAA' +
  'BwBXASYA6AABABYAAAH5AyoABgAAMwMzExMzA6iSmVdRopQDKv3aAib81gABABsAAAKeAyoADAAAMwMzExMzExMzAyMDA31imDA9' +
  'd0AxlmGcRUEDKv4oAdf+LAHV/NYB6f4XAAEABwAAAf0DKgALAAAzEwMzFzczAxMjJwcHnZapWUiVjp6oY1cBtAF229v+W/578vIA' +
  'AQAIAAAB5QMqAAgAADMRAzMTEzMDEaKaqU1FopcBSwHf/wABAP4h/rUAAQAdAAABlQMqAAkAADM1EyM1IRUDMxUdxr0BbcnLbAJF' +
  'eWX9tHkAAAIAFP/2AagCTAAlADIAABciJiY1ND4CNzU0JiYjIgYGBwcnNjYzMhYVERQWFhcjJiYnBgY3MjY2NzUOAxUUFposPB4r' +
  'RlQpBg4ODg8GAQSYBWVlWFcDBQKSAwgCCjcMChEOBRQiGA0YCipBIjZKMiMOOg8XDQwVDSoGaGNhTf7yJDYoDhc2BSQ4bggOB54M' +
  'GR4jFh0i//8AFP/2AagDSwImACAAAAAHAFcA7gAAAAIAM//2AdADKgAUACQAAAUiJicVIxEzETY2MzIeAhUVFAYGJzI2NjURNCYm' +
  'IyIGBxEWFgFSID8do6MeQR8hLx4OHTh4EBIICBEPDRcLCxcKHRksAyr+7hoaGi8+I/k2UC1pEh0SAQ4RGxALCP6YBwkAAAEAJ//2' +
  'AbICTAAmAAAXIiYmNTU0NjYzMhYWFRUjNTQmJiMiBgYVFRQWMzI2NjU1MxUUBgbvP1kwMFk/PlcunQkRDAwQCBMSDRAInS9XCi5W' +
  'PdQ+Vi0mTTs9QhcZCg0dGvAnHAsZFU1GOk8nAAIAKv/2AcUDKgASACEAABciJjU1NDY2MzIWFxEzESM1BgY3MjY3ESYmIyIGFREU' +
  'FhawQEYePCwgOhijoxs6KggXDAoWChYUCBIKWljvNlEuGRUBDPzWLRodaAgHAW0FCCUa/vYSHREAAgAn//YBsAJMAB0AKAAAFyIm' +
  'JjU1NDY2MzIWFhUVIxUUFhYzMjY2NTUzFRQGAzM1NCYmIyIGBhXwP1owMFs+QFUr6AoSDAwTC5ZmglILEw0MEQoKLVc91D5WLSxW' +
  'P3RvFhwMCxgVPThYWQFtOhcaCgwdG///ACf/9gGwA0sCJgAlAAAABwBXAO4AAAABABEAAAE0AxYAGAAAMxEjNTM1NDY2MzIWFxUm' +
  'JiMiBhUVMxUjEUg3NxVDRhMlFgcTCRIUSUkB1G4rM0wqAgN5AgMVGC5u/iwAAAQAGf84AgUCZQAsADwAUABZAAAXIiYmNTQ2NjcX' +
  'DgIVFBYzMjY1NCYmJycmJjU0NjcXBgYVFBYXFxYWFRQGBgMiJiY1NDY2MzIWFhUUBgYnMj4CNTQuAiMiDgIVFB4CNyc2NjcXDgLw' +
  'QWE1GzEfPwsTDDI6MDUOIByQLjYrIzkMDhgfiUpFMW1QRF0vMF1DQFgvLVhCDhEJBAQJEQ4NEgoEBAkSsiIPLSYnCicpyBo0Jx4v' +
  'IgwLCRMVDhYWERkOEAoDEgY2KCM8HSAMFQ0MDgQSCVA/OEwnAYMwWT9BWi4wWUA/WTBhCxgoHB0nGQsLGCgdHCcZC8ssHSMSTgMR' +
  'FAABADQAAAHOAyoAFAAAMxEzETY2MzIWFhURIxE0JiMiBgcRNKIgRigjLxiiDhMKHA8DKv7lIB0jPSf+OwGuFRYLCv48AAIAMwAA' +
  'ANcDFQADAAcAADMRMxEDNTMVNKOkpAJC/b4CpHFxAAEAOwAAAN4CQgADAAAzETMRO6MCQv2+//8AOwAAATwDSwImACsAAAAHAFcA' +
  'jQAA//8AOwAAAN4DJgImACsAAAAHAFYAjQAAAAL/7/9MANwDFQAQABQAABciJic1FhYzMjY2NREzERQGAzUzFUYWLRQIDwYOFAui' +
  'S1iktAcGdQEDChUSAkf9pURXA1hxcQABADMAAAH7AyoACwAAMxEzETczBxMjAwcVM512tYuKsFYkAyr+P9nt/qsBEzfcAAABADoA' +
  'AADcAyoAAwAAMxEzETqiAyr81gABADMAAALCAk0AJgAAMxEzFTY2MzIWFzY2MzIWFhURIxE0JiMiBgcUFBURIxE0JiMiBgcRM6Ag' +
  'RSQjMw0iSyYiMhygEREKHg6eEhELHQ4CQi4fGiMiJh8hPyz+PwGwGBULCgIDAv4/AbAYFQsK/jgAAQAzAAABzAJMABQAADMRMxU2' +
  'NjMyFhYVESMRNCYjIgYHETOjIEUmJC8Yog4TChsOAkI6ICQjPSf+OwGuFRYLCv48AAACACf/9gG8AkwAEQAjAAAXIiYmNTU0NjYz' +
  'MhYWFRUUBgYnMjY2NTU0JiYjIgYGFRUUFhbxPlsxMVs+PlsyMls9EBIHBxIQEBIICBIKKlQ/3D9UKipUP9w/VCpsER8W8hYfEREf' +
  'FvIWHxH//wAn//YBvANLAiYAMwAAAAcAVwDxAAAAAgAz/0IBzwJMABQAJAAAFxEzFTY2MzIeAhUVFAYGIyImJxUTMjY2NRE0JiYj' +
  'IgYHERYWM6MdQh4hLx4OHTgpHz8dKxASCQgSDg0XCgsVvgMAKhoaGi8+I/k2UC0dGeoBHRIdEgEOERsQCwn+mAcIAAIAKv9CAccC' +
  'TAASACEAAAU1BgYjIiY1NTQ2NjMyFhc1MxEDMjY3ESYmIyIGFREUFhYBJBw6HkFFHjwsIToZo88JFwwKFgsXFQkTvu4bH1pY7zZR' +
  'LhoXJ/0AARwJBwFqBwglGv72Eh0RAAABADUAAAFtAkkAEQAAMxEzFTY2MzIWFxUmJiMiBgcRNaMcOCgIDAULGw8cMBQCQmAyNQEC' +
  'ogUHHhr+iAABABT/9gGWAkwAKwAAFyImJzcWFjMyNjU0JicnJiY1NDY2MzIWFwcuAiMiBhUUFhcXHgIVFAYG5UxlIG8QKxoTEyMt' +
  'Ki41MVIvSGAUawYWHhMQEysmKRkwHzJRCkRNMSctEA4XJiUjJ0k2L0goTkcwEyYaEg8TLB8kFTA6JTJHJAAAAQAO//oBSgLyABgA' +
  'ABciJiY1ESM1MzUzFTMVIxEUFjMyNjcVBgboQUYbODilUlIdFg0WCQ04BiZJNAE6a7Cwa/7WGRYDAYACBgABAC3/9gHEAkIAFAAA' +
  'FyImJjURMxEUFjMyNjcRMxEjNQYGmSMxGKMPEwsYDaKiH0UKIz4mAcX+ThUXCwcBzP2+NR0i//8ALf/2AcQDSwImADoAAAAHAFcA' +
  '/AAAAAEACgAAAZ4CQgAGAAAzAzMTEzMDfnScMCycdwJC/o8Bcf2+AAEAFQAAAkACQgAMAAAzAzMTEzMTEzMDIwMDalWIKi12JzF+' +
  'VowyOAJC/rgBSP6wAVD9vgFF/rsAAQALAAABuAJCAAsAADMTAzMXNzMDEyMnBwt7daQ+N31yg6ZGOgE9AQWLi/7j/tufnwABAAP/' +
  'WAG2AkIAEgAAFzUyNjY1NCYnAzMTEzMDDgIjQx8pFQwJiJlJN5qFDThRM6hxCBYTETEfAef+sgFO/bA8QxsAAAEAIwAAAW4CQgAJ' +
  'AAAzNRMjNSEVAzMVI5+TAT2ho2kBYndj/ph3AP//ABEAAAJUAxYAJgAnAAAABwAnASAAAAACAAoAAAL1AxYALwAzAAAzESM1MzU0' +
  'NjYzMhYXFSYmIyIGFRUzNTQ2NjMyFhcVJiYjIgYVFSERIxEjESMRIxEBNTMVQjg4FURGEhsVBxAHEBFnFURGEh0WBxEIEBEBB6Jl' +
  'o2cBfZQB1mwrM0wqAgN5AgIUGC4rM0wqAgN5AgIUGC79vgHW/ioB1v4qAqRxcQABABEAAAMkAycAMQAAATIWFxEjESYiIyIGBhUV' +
  'MxUjESMRIxEjESM1MzU0NjYzMhYXFSYmIyIGFRUzNTQ+AgJRKmlAowoRCCYiCT4+o3+jNzcVQ0YTJRYHEwkSFH8MLF4DJwoM/O8C' +
  'uAIVIxYqbv4sAdT+LAHUbiszTCoCA3kCAxUYLishQTchAAACAA4AAAH1AxcAGgAeAAAzESM1MzU0NjYzMhYXFSYmIyIGFRUhESMR' +
  'IxETNTMVRTc3G0M8ECMTBQwGERUBDaFsdpcB1G4rNEwqAwNvAQEUHTH9vgHU/iwCpHFxAAEACgAAAfsDJwAeAAAzESM1MzU0PgIz' +
  'MhYXESMRJiIjIgYGFRQUFTMVIxFCODgMLF1RKmlAogoSCCYiCT4+AdByKyFBNyEKDPzvArgCFSMWChULcv4wAAACADb/8QHvAzYA' +
  'EQAjAAAFIiYmNRE0NjYzMhYWFREUBgYnMjY2NRE0JiYjIgYGFREUFhYBE0liMi9iTExhLzJiSBgVBQQVGRkVBAYVDztoRQFvR2s8' +
  'PGtH/pFEaTuVHykPAWcRKyEhKxH+mQ8pHwAAAQAWAAABLAMqAA4AADMRDgMHNT4DNzMRhQscHx0MCyguKAqDAoUGDA0MBnwGFRob' +
  'CvzWAAEAJwAAAeYDNQAeAAAzNRM+AjU0JiMiBgYVFSM1NDY2MzIWFRQGBgcHMxUpwhYnGRwYGx4Loi5kUW1vHzMdlO12ASohPkAj' +
  'IyIeMh8oK0hxQXFlMVRPK92DAAEAJv/xAeMDNgA7AAAFIiYmNTUzFBQVFBYWMzI2NjU0JiciIiM1MjIzMjY1NCYjIgYVFBQVIzU0' +
  'NjYzMhYWFRQGBx4CFRQGBgEFVWEppwoaFxcXCCE0ARQKBw4GNSQZIiEVpzVjRUZkNjopHC0aK2IPQHNLHQEUCCgyFxgwJDw/AXM6' +
  'PS8yOCwKFQsxSWU0MmFIR2ALCixLOkpyQQAAAgAZAAAB+QMqAAoADQAAITUjNRMzETMVIxUBMxEBEvnTwktL/up6tnsB+f4IfLYB' +
  'MgFRAAEAK//xAdwDKgAlAAAXIiYmNTMUFhY3PgI1NCYmIyIGByMTIRUjBzY2NzYWFhUUDgL/WVsgoQobGRoWBQkbGxkgB5APAXr0' +
  'CQo4ID5VKxAuWA8/cksuOhkBAShLNSg+JSQmAdOMpw4VAwc7eFdBbU8sAAIANP/0AfEDNQAjADQAAAUiJiY1ETQ2NjMyFhYVFBYV' +
  'IzQmIyIGBhUVNjY3NhYWFRQGBicyNjY1NCYmIyIGBgcVFBYWARRPYy4lYFpOWiYBnQ8iFxcIDDYiQE0iKGBTFxUHBRYaDBYQBAkZ' +
  'DEV4TQElT3xHMFxEBAcDMS8cRj9IFRcBAj5rQlWBSHsfPS0oOiEKDweEGzAdAAABABQAAAGUAyoABgAAMxMjNSEVA0Gw3QGAsAKr' +
  'f3P9SQAAAwAm//MB5AM1AB8ALwA9AAAFIiYmNT4DNyYmJyY2NjMyFhYHBgYHHgMVFgYGJzI2NjU2JiYjIgYGFRQWFhMyNjY1NCYj' +
  'IgYVFBYWAQRSYioBCxcjGB8wAgEvXkVGXS4CAS4gGCMXDAIrYlMbGAYBBxgbGhgHBhkaERYLGRkZGwsYDUFzSh45MSUMF1dDRGI0' +
  'NWFERFcWDCUxOR5Kc0F7KDcXHzolJTkgFzgnAXgbNigpMDAoKDcbAAIAJ//0AeQDNQAjADMAAAUiJiY1NDQ1MxQWMzI2NjU1BgYH' +
  'BiYmNTQ2NjMyFhYVERQGBgMyNjc1NCYmIyIGBhUUFhYBBU5aJpwRIhcWBw01IUBOIitiUVBiLSVgWBQYBwgWFxYWBwUWDDBdRAMH' +
  'AzEvHEc+SBUWAgFCcEJVe0RAc07+0k98RwG6FgqEHC8dHz0tJzshAAEALgAAAMgAmgADAAAzNTMVLpqamgABACv/dADGAJoACgAA' +
  'Fyc2NjUjNTMVBgZEChotVpsBQIw1ByUrmoVKUgABACUBLAC/AcQAAwAAEzUzFSWaASyYmAABADYBLAClAcQAAwAAEzUzFTZvASyY' +
  'mAABACAA8gEkAVsAAwAANzUhFSABBPJpaQAFAC3//wPAAysAAwARACEALwA/AAAhEzMDAyImNTU0NjMyFhUVFAYnMjY2NTU0JiMi' +
  'BhUVFBYWASImNTU0NjMyFhUVFAYnMjY2NTU0JiMiBhUVFBYWAUz5Wvi9Z1ZUaWlVVmgaFwYOKSgPBhgCMWdVU2lpVVZoGhcGDiko' +
  'DwYYAyr81gFea2wkbmRibihramgbNSUZOTU0ORslNBv+OWtsJG5kYm4nbGpoGzQlGzk0NDkbJTQbAAH/swKMAE0DJgADAAADNTMV' +
  'TZoCjJqaAAH/ygKCAK8DSwADAAADNzMHNj+mfgKCyckAAAABAAAAWABlAAcAaAAFAAEAAAAAAAAAAAAAAAAAAwABAAAAAAAYACQA' +
  'YACZAL8A0wDfAPIBLwFFAVEBXQF2AY8BnQG5Ac4CBgISAjgCgAKqAu4C/wMjAy8DQQNdA3YDiwOfA+oD9gQvBGUEmQTTBN8FBAWE' +
  'BaYFuAXEBdAF3AX/BhcGIwZbBn0Gsga+BvYHKwdJB4oHrwfRB90H7wgLCCQIRghaCGYIrgjzCSEJTQmFCZ8JzAobCjUKbgq7CswL' +
  'KAtzC34LkwufC6sLtwwSDB4MKwAAAAEAAAAEGl7uVFQYXw889QADA+gAAAAA1eqgZQAAAADg3uem/yH+mwVuBSYAAQAGAAIAAAAA' +
  'AAACmwBSAicAFQInABUCTAA8AjMAMQJKADwBvwA8Ab8APAGyADwCRgAxAmIAPwEtAD0BLQA9AV0ADQI3ADwBuwA8AsAAOQIxADwC' +
  'SgAxAkoAMQI7ADwCSgAxAlgAPAICACoBvQALAkwANgJMADYCDgAWArkAGwIDAAcB7QAIAbEAHQHMABQBzAAUAfoAMwHUACcB9wAq' +
  'AdYAJwHWACcBQAARAfYAGQH9ADQBCQAzARgAOwEYADsBGAA7AQ3/7wH+ADMBEgA6AvEAMwH7ADMB4wAnAeMAJwH5ADMB+AAqAX8A' +
  'NQGoABQBXwAOAfgALQH4AC0BpQAKAlUAFQG6AAsBwAADAYgAIwJgABEDIwAKA1oAEQInAA4CJwAKAiYANgGBABYCAgAnAgIAJgIM' +
  'ABkB/QArAhoANAG3ABQCCQAmAhoAJwD0AC4A7gArAOIAJQDbADYBRAAgA+4ALQAA/7P/ygAAAAEAAASp/t8AAAWf/yH+QgVuAAEA' +
  'AAAAAAAAAAAAAAAAAABXAAQCBQK8AAUAAAKKAlgAAABLAooCWAAAAV4AMgFbAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAG5l' +
  'd3QAoAAlAPoEqf7fAAAFLQF5AAAAAQAAAAACQgMqAAAAIAADAAAAAgAAAAMAAAAUAAMAAQAAABQABAECAAAAJgAgAAQABgAlAC4A' +
  'OQBVAFoAdQB6ALcAwQDJAM0A0wDaAOEA6QDtAPMA+v//AAAAJQAsADAAQQBWAGEAdgC3AMEAyQDNANMA2gDhAOkA7QDzAPr//wAw' +
  'AAAAFgAA/8UAAP/G/5v/Qf8+/z//QP9A/0D/Pf8//0H/QQABAAAAJAAAACYAAABMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'UQBUAFAAAQADAAQABQAGAAgACQAKAAsADQAOAA8AEAARABIAFAAVABYAFwAYABkAIAAiACMAJAAlACcAKAApACoALgAvADAAMQAy' +
  'ADMANQA2ADcAOAA5ADoAAAAAAAkAcgADAAEECQAAAKoAAAADAAEECQABAAwAqgADAAEECQACAAgAtgADAAEECQADACwAvgADAAEE' +
  'CQAEABYA6gADAAEECQAFAFYBAAADAAEECQAGABYBVgADAAEECQEAAAwBbAADAAEECQEGAAgAtgBDAG8AcAB5AHIAaQBnAGgAdAAg' +
  'ADIAMAAxADYAIABUAGgAZQAgAE8AcwB3AGEAbABkACAAUAByAG8AagBlAGMAdAAgAEEAdQB0AGgAbwByAHMAIAAoAGgAdAB0AHAA' +
  'cwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AZwBvAG8AZwBsAGUAZgBvAG4AdABzAC8ATwBzAHcAYQBsAGQARgBvAG4AdAAp' +
  'AE8AcwB3AGEAbABkAEIAbwBsAGQANAAuADEAMAAzADsAbgBlAHcAdAA7AE8AcwB3AGEAbABkAC0AQgBvAGwAZABPAHMAdwBhAGwA' +
  'ZAAgAEIAbwBsAGQAVgBlAHIAcwBpAG8AbgAgADQALgAxADAAMwA7AGcAZgB0AG8AbwBsAHMAWwAwAC4AOQAuADMAMwAuAGQAZQB2' +
  'ADgAKwBnADAAMgA5AGUAMQA5AGYAXQBPAHMAdwBhAGwAZAAtAEIAbwBsAGQAVwBlAGkAZwBoAHQAAAADAAAAAAAA/5wAMgAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAEAAf//AA8AAQAAAAwAAAAuAAAAAgAFAAEAKgABACwALQABAC8AQAABAEEARQACAFMAUwABAA4ABQAY' +
  'ACAALgA8ADwAAgABAEEARQAAAAEABAABATAAAgAGAAoAAQEMAAECGAACAAYACgABAR4AAQI8AAEABAABARQAAAABAAAACgAkADIA' +
  'AkRGTFQADmxhdG4ADgAEAAAAAP//AAEAAAABa2VybgAIAAAAAQAAAAEABAACAAgAAgAKBBoAAQCKAAQAAABAANAA0ADeAOgBSgDu' +
  'APQA+gEIASIBSgFKASgBSgFYAV4BaAF2AggCGgKcAroCugL4AsQCzgLUAtQDigLeAvIC7AOUAvIC8gL4AvgC+AMGAwwDFgMgAyYD' +
  'JgMsAz4DTAN6A4QDigOUA5QDmgOoA64DtAO+A8QD2gPgA+oD8APwA/oAAgALAAEABQAAAAgACQAFAA4AEAAHABIAGAAKABsAHgAR' +
  'ACAAKQAVAC8AQQAfAEMAQwAyAEUASAAzAEoAUQA3AFQAVAA/AAMAFQAAABv/3gA8//4AAgAb/+kAHf/sAAEAHf/4AAEAPv/+AAEA' +
  'G//3AAMAFf/qADz//wBU/+YABgAV/+8AG/+7AEf/3gBN//gAUv+zAFT/1QABABv/+AAIAB3/7wA2AAAAPv/4AEr/+gBN//gAUP+u' +
  'AFH/ugBU/80AAwAb//gAHf/vAE3/+AABABv/9AACABv/+AAd//gAAwA2AAAAPv/WAFT/1QAkAAH/3gAC/94ABP/3AAn/9wAN//sA' +
  'EP/4ABL/9wAT//cAFf/3ABf/+QAg/9EAIf/RACP/3QAk/90AJf/dACb/3QAo/9QAMf/kADL/5AAz/90ANP/dADX/6AA2/+EAN//k' +
  'ADj/4wA5//4AOv/qADv/6gA8//QAPf/sAD7/5AA///EAQP/YAFD/xwBR/8cAVP/qAAQANgAAADz//gA+//4AVP/4ACAABP/vAAn/' +
  '7wAS/+8AE//vABX/7wAX//EAIP/+ACH//gAj//YAJP/2ACX/9gAm//YAJ//7ACj//gAxAAAAMgAAADP/9gA0//YANv/2ADcAAAA4' +
  '//QAOf/7ADz/5AA9/+oAP//iAEH/+wBC//sAQ//7AET/+wBF//sARv/4AFT/7wAHADb/9QA+/9gARv/vAEr/5gBM//gATv/4AFT/' +
  '1QACABv/1gA8//8AAgAb/+oAUQAAAAEAGwAaAAIAG//nAD7/9QADABv//gAd//sANgAAAAEAG//wAAEAG//iAAMAG//gAB3/+AA+' +
  '//0AAQAb//sAAgAd/+QANv/rAAIAG//nAB3//gABABv/8QABABv/7AAEABv/7AAd/+QAUP/XAFH/1wADABv/7AAd/+oAUf/tAAsA' +
  'GP/WABv/5AAc//4AHv/YACP/+AAk//gAJf/4ACb/+AAz//gANP/4ADb/+AACABv/7AAd/+QAAQAb/+0AAgBQ/+YAUQAAAAEAGwAQ' +
  'AAMAHf/4AB7/7wBN//4AAQBN//0AAQBK/+8AAgBH/+8ATf/0AAEATf/vAAUAHv/4AEf/+ABI//gATf/2AE//8wABAEr/6QACAB7/' +
  '+ABN//UAAQBN/+4AAgAb/9AAPP/8AAUAGP/VABv/6gAc//gAHf/vAB7/1QACCBQABAAACFQI/AAmABsAAAAAAAAAAAAA//MAAAAA' +
  'AAAAAAAA/+8AAAAAAAAAAP/4AAAAAAAA//j/7wAAAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8QAAAAAAAAAAP/LAAD/' +
  '8gAAAAD//gAA//8AAAAAAAAAAAAAAAD/8wAAAAD/+AAAAAAAAP/y/9T/6wAA//gAAP/T//P/7P/tAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAA/8b//AAAAAAAAP/MAAD/7v/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8QA' +
  'AAAAAAAAAP/LAAD/+gAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAA//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7wAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/80AAAAAAAAAAP/NAAD/+QAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAP//AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8cAAAAAAAAAAP/M' +
  'AAD/7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/z/+UAAAAAAAAAAAAA/9oAAP/1AAAAAP/JAAD//gAA/+z/3AAAAAD/5gAAAAAA' +
  'AAAA/8T/7//B/9QAAP/N/8cAAP/bAAD/4v/D//j/zQAAAAAAAP/ZAAD/s//bAAD/+//4/9MAAAAA//sAAAAAAAAAAAAAAAAAAAAA' +
  '/9sAAP/4AAAAAP/WAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP/2AAAAAP/6AAAAAAAA//YADv/+AAAAAP/wAAgAAAAI//4A' +
  'AAAAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAP/wAAD//QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  '//gAAAAAAAAAAAAA//gAAAAA/+8AAAAAAAAAAAAAAAAAAAAAAAAAAP/4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8gAAAAAAAAA' +
  'AP/PAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//wAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAAAAAAAA' +
  'AAAAAAAA//j/+P/4AAAAAAAAAAAAAAAAAAAAAAAA//oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+z/+P/2AAD/+gAAAAAA' +
  'AAAA/+n/+AAA//wAAP/1AAD//f/+AAAAAP/vAAAAAAAAAAAAAAAA/8v/+P+6/9MAAP/W/8wAAP/pAAD/0//IAAD/wwAA//QAAP/L' +
  'AAD/xv/V//3/5P/6/8wAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9AAAAAAAAAAAP/WAAD//AAAAAAAAAAA//8AAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAABcAAAAAAAAAAAAfAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP/v/+QAAAAAAAAAAAAA/+UAAP/3' +
  'AAAAAP/VAAAAAAAA/+z/ogAAAAD/5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+YAAP/4//oAAP/6AAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2wAAAAAAAAAAAAAAAAAA//AAAP/q/+wAAAAA' +
  '/+4AAP/4AAAAAP/k//z/+gAAAAAAAP/+AAD/2f/+AAAAAAAA//YAAAAAAAAAAP/z/+4AAAAAAAAAAAAA/9oAAP/4AAAAAP/LAAD/' +
  '/gAA/+//7AAAAAD/4gAAAAAAAAAA////8wAAAAD/7gAAAAAAAP/u/6z/x/////j///+7/+b/0//hAAAAAAAAAAAAAAAAAAAAAP/4' +
  '//7/7wAAAAD/7wAAAAAAAAAA/8r/5gAAAAAAAP/G/+b/2f/vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwA' +
  'AAAAAAAAAAAuAAAAGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAP/0//gAAAACAAAAA//gAAAAAAAAAAAAAAAAAAAAAAAAAAD//AAA' +
  'AAMAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAAAA/9sAAP/4AAD/+P/aAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAA//H/6QACAAAA' +
  'AP/1AAAAAAAAAAD/2////+3//wAA/+8AAP/mAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAA/+UAAAAAAAAAAP/s' +
  'AAD/+wAAAAD/7wAAAAAAAAAAAAAAAAAA//UAAP/s/98AAAAAAAAAAAAAAAD//v/+//r/8wAAAAAAAAAAAAD/rv/uAAD/6gAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAA//gAAAAA//MAAP/6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+oAAP/b/9AAAAAA//4AAAAA' +
  'AAAAAP/l//j/5gAAAAAAAAAA//r/av/vAAD/4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9kAAAAAAAAAAP/OAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAgAKAAEACQAAAA0AEAAJABIAGgANABwAHAAWAB4AKQAXAC8APQAjAD8AQQAyAEMAQwA1AEUARQA2AFAAUQA3' +
  'AAEAAQBRAAIAAgAhABAAAAAHAAcAIgANAAAAAAAAABgAIAAbACMAAAAAAAAAJAAAABIADgATAAUABQAAABkAAAAKABEAAwADAAEA' +
  'FAAdAAQABAAeAAwACAAAAAAAAAAAAAAAHwAVAAgACAABAAEAAQAlABYADwAXAAYABgAJABoAAAAJAAsAHgAAABUAAAAVAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAHAAcAAEAAQBRAAUABQABAAMAAQABAAEAAQADAAEAAQABABgAAQABABkAAQADAAMAAQADAAEADgAQAAYA' +
  'BgAAABIAAAALABQABAAEAAAAAgACAAIAAgAKAA0AAAAJAAAACQAJABcAAAAAAAgACAACAAIAGgACAAgADwARAAcABwAAABMAAAAM' +
  'ABYACgAKAAoACgAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAFQAVAAEAAAAKAHwAvAACREZMVAAObGF0bgASAE4AAAA0AAhBWkUgAFRD' +
  'QVQgAD5DUlQgAFRLQVogAFRNT0wgAEpST00gAEpUQVQgAFRUUksgAFQAAP//AAIAAQACAAD//wADAAAAAgAEAAD//wACAAAAAgAA' +
  '//8AAwAAAAIAAwAFY2NtcAAgY2NtcAAmbGlnYQAubG9jbAA0bG9jbAA6AAAAAQAAAAAAAgAAAAAAAAABAAQAAAABAAEAAAABAAIA' +
  'BQAMADIARgB8AJAAAgAIAAEACAABAAoAAgASABgAAQACAEQARQACACcAKgACACcAMAABAAAAAQAIAAEABgADAAEAAQAqAAYAAAAB' +
  'AAgAAQA8AAEACAACAAYAFgABADAAAQABADAAAQAAAAMAAQAPAAEAAQAPAAEAAAADAAEAAAABAAgAAQAGAAEAAQABAFIABAAIAAEA' +
  'CAABADYAAQAIAAUADAAUABwAIgAoAEIAAwAnACoAQwADACcAMABBAAIAJwBEAAIAKgBFAAIAMAABAAEAJwABAAEACAABAAAAFAAB' +
  'AAAAHAACd2dodAEAAAAAAgABAAAAAAEGArwAAAAA';

const OSWALD_BUFFER = (() => {
  const bin = atob(OSWALD_B64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  return buf;
})();

// Inicializa el WASM una sola vez por isolate.
let wasmReady = null;
function ensureWasm() {
  if (!wasmReady) wasmReady = initWasm(resvgWasm);
  return wasmReady;
}

// Fechas del mandato en hora de Chile (UTC-3, sin DST para simplificar)
const START_ISO  = '2026-03-11T00:00:00-03:00';
const TARGET_ISO = '2030-03-11T00:00:00-03:00';

// Paleta
const BG      = '#0d0d0d';
const RED     = '#C41E3A';
const WHITE   = '#f5f3ee';
const MUTED   = '#888888';
const BORDER  = '#2a2a2a';

// Ancho máximo de la barra de progreso (px dentro del SVG)
const BAR_MAX_W = 880;

// ─── Función exportada — llamada desde worker.js ──────────────────────────

export async function buildOGResponse() {
  await ensureWasm();

  const now    = new Date();
  const start  = new Date(START_ISO);
  const target = new Date(TARGET_ISO);

  const totalMs   = target.getTime() - start.getTime();
  const remainMs  = Math.max(0, target.getTime() - now.getTime());
  const elapsedMs = Math.max(0, now.getTime() - start.getTime());

  const days  = Math.floor(remainMs / 86_400_000);
  const pct   = Math.max(0, (remainMs  / totalMs) * 100).toFixed(1);
  const barW  = Math.min(BAR_MAX_W, Math.round((elapsedMs / totalMs) * BAR_MAX_W));

  const svg = buildSVG(days, pct, barW);

  const resvg = new Resvg(svg, {
    fitTo: { mode: 'original' },
    font: {
      loadSystemFonts: false,   // no buscar fuentes del sistema (no existen en Workers)
      fontBuffers:    [OSWALD_BUFFER],
    },
  });
  const rendered = resvg.render();
  const png      = rendered.asPng();   // Uint8Array — dimensiones garantizadas 1200×630

  return new Response(png, {
    headers: {
      'Content-Type':           'image/png',
      'Content-Disposition':    'inline',
      'Cache-Control':          'public, max-age=3600',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

// ─── Generador SVG ────────────────────────────────────────────────────────
// Todas las fuentes usan 'Oswald' — embedida arriba, garantizada en render.

function buildSVG(days, pct, barW) {
  const numLetterSpacing = days >= 1000 ? '-2' : '2';

  return `<svg xmlns="http://www.w3.org/2000/svg"
  width="1200" height="630" viewBox="0 0 1200 630">

  <!-- ── Fondo ──────────────────────────────────────────────── -->
  <rect width="1200" height="630" fill="${BG}"/>

  <!-- ── Marco rojo (top / bottom / left / right) ──────────── -->
  <rect x="0"    y="0"   width="1200" height="8"   fill="${RED}"/>
  <rect x="0"    y="622" width="1200" height="8"   fill="${RED}"/>
  <rect x="0"    y="8"   width="6"    height="614" fill="${RED}"/>
  <rect x="1194" y="8"   width="6"    height="614" fill="${RED}"/>

  <!-- ── Cabecera ───────────────────────────────────────────── -->
  <text
    x="80" y="66"
    font-family="'Oswald', sans-serif"
    font-size="13" font-weight="700"
    letter-spacing="5"
    fill="${RED}">YAFALTAMENOS.CL</text>

  <!-- Separador header -->
  <line x1="80" y1="84" x2="1120" y2="84" stroke="${BORDER}" stroke-width="1"/>

  <!-- ── Bloque central: número grande ─────────────────────── -->
  <!-- Sombra sutil del número -->
  <text
    x="83" y="403"
    font-family="'Oswald', sans-serif"
    font-size="290" font-weight="700"
    letter-spacing="${numLetterSpacing}"
    fill="#1a0005"
    aria-hidden="true">${days}</text>

  <!-- Número principal -->
  <text
    x="80" y="400"
    font-family="'Oswald', sans-serif"
    font-size="290" font-weight="700"
    letter-spacing="${numLetterSpacing}"
    fill="${WHITE}">${days}</text>

  <!-- Etiqueta DÍAS — pegada bajo el número, blanca -->
  <text
    x="80" y="445"
    font-family="'Oswald', sans-serif"
    font-size="54" font-weight="700"
    letter-spacing="20"
    fill="${WHITE}">D\u00CDAS</text>

  <!-- Subtítulo -->
  <text
    x="80" y="504"
    font-family="'Oswald', sans-serif"
    font-size="14" font-weight="700"
    letter-spacing="4"
    fill="${MUTED}">PARA EL \u00DALTIMO D\u00CDA DEL GOBIERNO</text>

  <!-- ── Separador + barra de progreso ─────────────────────── -->
  <line x1="80" y1="526" x2="1120" y2="526" stroke="${BORDER}" stroke-width="1"/>

  <!-- Track de progreso -->
  <rect x="80" y="539" width="${BAR_MAX_W}" height="10" rx="3" fill="#333333"/>
  <!-- Fill de progreso -->
  <rect x="80" y="539" width="${barW}" height="10" rx="3" fill="${RED}"/>

  <!-- ── Fila inferior ──────────────────────────────────────── -->
  <text
    x="80" y="602"
    font-family="'Oswald', sans-serif"
    font-size="16" font-weight="700"
    letter-spacing="1"
    fill="${MUTED}">${pct}% restante · la cuenta regresiva ya empez\u00F3</text>

  <!-- Fecha objetivo (derecha) -->
  <text
    x="1120" y="602"
    font-family="'Oswald', sans-serif"
    font-size="26" font-weight="700"
    letter-spacing="4"
    text-anchor="end"
    fill="${WHITE}">11 \u00B7 03 \u00B7 2030</text>

</svg>`;
}
